apiVersion: v1
kind: Service
metadata:
  name: registry-cache
  labels:
    app: registry-cache
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  selector:
    app: registry-cache
    release: {{ .Release.Name }}
  ports:
  - name: registry-cache
    port: 4000
    protocol: TCP
